In [13]:
%cd ..
!mv LLaMA LLaMA_main

/kaggle/working


In [ ]:
%cd ..
!rm -rf LLaMA
!git clone https://github.com/TmBoris/LLaMA.git

/home/jupyter/work/resources/hw3_llama


Cloning into 'LLaMA'...


In [1]:
!pwd
!ls

/home/jupyter/work/resources/hw3_llama
LLaMA
LLaMA_main
starter.ipynb
tinyBenchmarks.pkl


In [20]:
!rm LLaMA_main/train.py LLaMA_main/inference.py
!rm -rf LLaMA_main/src
!cp LLaMA/train.py LLaMA_main/train.py
!cp LLaMA/inference.py LLaMA_main/inference.py
!cp -r LLaMA/src LLaMA_main/src

In [2]:
%cd LLaMA_main
# %cd LLaMA

/home/jupyter/work/resources/hw3_llama/LLaMA_main


In [39]:
# %pip install -r requirements.txt

In [40]:
import os
os.environ["PATH"] += os.pathsep + '/home/jupyter/.local/bin'

In [41]:
from huggingface_hub import login

login(token="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")

In [29]:
import wandb

wandb.login(key="46c3b8e339b3fb22dc286204510c8af5b2c3e2e5")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /home/jupyter/.netrc


True

In [30]:
# !HYDRA_FULL_ERROR=1 python3 train.py writer.run_name=big_pretrain_ds_bs3_compile dataloader.batch_size=3 lr_scheduler.max_lr=5e-5 trainer.amp=False model.use_xformers=False trainer.resume_from=checkpoint-epoch45.pth  # pretrain

In [3]:
!HYDRA_FULL_ERROR=1 python3 train.py writer.run_name=fine_tune_v10 dataloader.batch_size=3 lr_scheduler.max_lr=2e-5 trainer.amp=False model.use_xformers=False +trainer.from_pretrained=saved/big_pretrain_ds_bs3_compile/checkpoint-epoch100.pth trainer.n_epochs=10

^C


TypeError: cannot unpack non-iterable NoneType object

In [6]:
from src.model.LLaMA_config import LLaMA_config

llama_config = LLaMA_config()
llama_config.register_for_auto_class()

/home/jupyter/.local/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-11-08 17:14:43.828995: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appr

In [7]:
from src.model.LLaMA_model import LLaMA_model

llama_model = LLaMA_model(llama_config)
llama_model.register_for_auto_class("AutoModelForCausalLM")

model initialized


In [3]:
import torch

saved_state_dict = torch.load('saved/big_pretrain_ds_bs3_compile/checkpoint-epoch100.pth')["state_dict"]

/tmp/ipykernel_15372/3377449557.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  saved_state_dict = torch.load('saved/big_pretrain_ds_bs3_compile/checkpoint-epoch100.pth'

In [7]:
saved_state_dict

OrderedDict([('_orig_mod.embeds.weight',
              tensor([[-1.5232, -0.7491, -0.6530,  ..., -1.1418,  0.7875, -0.6758],
                      [-0.9313,  0.0741,  0.2100,  ...,  1.8626, -0.0840, -1.5308],
                      [ 0.7081,  0.6274,  1.7001,  ...,  1.0639, -0.3628,  0.0315],
                      ...,
                      [ 1.2412, -2.0930,  1.7992,  ..., -0.0896, -0.1240,  0.1668],
                      [-0.9807,  0.8850, -0.6403,  ...,  0.0284,  1.9486, -0.4074],
                      [ 0.8466,  0.5214, -0.9407,  ..., -1.4049, -1.1510,  0.2065]],
                     device='cuda:0')),
             ('_orig_mod.blocks.0.rms.weight',
              tensor([[0.9916, 0.9949, 1.0026,  ..., 1.0032, 1.0007, 1.0076],
                      [1.0646, 0.9628, 0.9566,  ..., 0.8962, 0.9586, 0.9045],
                      [0.9778, 0.9606, 0.9695,  ..., 0.9616, 0.9751, 0.9698],
                      ...,
                      [1.0184, 1.0158, 1.0199,  ..., 1.0282, 1.0300, 1.0083],
 

In [8]:
from collections import OrderedDict 

new_state_dict = OrderedDict()
for k, v in saved_state_dict.items():
    if 'rms.weight' in k:
        v = torch.randn(v.shape[-1], device=v.device)
    new_state_dict[k] = v

In [9]:
new_state_dict

OrderedDict([('_orig_mod.embeds.weight',
              tensor([[-1.5232, -0.7491, -0.6530,  ..., -1.1418,  0.7875, -0.6758],
                      [-0.9313,  0.0741,  0.2100,  ...,  1.8626, -0.0840, -1.5308],
                      [ 0.7081,  0.6274,  1.7001,  ...,  1.0639, -0.3628,  0.0315],
                      ...,
                      [ 1.2412, -2.0930,  1.7992,  ..., -0.0896, -0.1240,  0.1668],
                      [-0.9807,  0.8850, -0.6403,  ...,  0.0284,  1.9486, -0.4074],
                      [ 0.8466,  0.5214, -0.9407,  ..., -1.4049, -1.1510,  0.2065]],
                     device='cuda:0')),
             ('_orig_mod.blocks.0.rms.weight',
              tensor([ 1.5485e+00,  9.4413e-01,  6.3946e-01,  1.1023e+00, -7.2955e-01,
                       9.9417e-02,  1.8085e-02, -1.0384e+00,  9.2972e-01,  1.8818e-01,
                      -6.4014e-01,  1.1983e-01,  5.3361e-01,  1.7634e+00,  1.3997e+00,
                       4.7609e-01, -1.4024e+00,  1.9444e-01, -2.9347e-01,  1.88

In [9]:
from collections import OrderedDict 
new_state_dict = OrderedDict()
for k, v in saved_state_dict.items():
    name = k.replace("_orig_mod.", "")  # Убираем префикс
    new_state_dict[name] = v

In [10]:
llama_model.model.load_state_dict(new_state_dict)

<All keys matched successfully>

In [11]:
llama_config

LLaMA_config {
  "_attn_implementation_autoset": true,
  "d_model": 768,
  "expected_seq_len": 1024,
  "inter_dim": 1024,
  "model_type": "llama",
  "n_heads": 16,
  "n_layers": 16,
  "seq_len": 256,
  "transformers_version": "4.46.1",
  "use_xformers": false,
  "vocab_size": 32000
}

In [12]:
llama_model

LLaMA_model(
  (model): LLaMA(
    (embeds): Embedding(32000, 768)
    (blocks): ModuleList(
      (0-15): 16 x LlamaBlock(
        (rms): RMSNorm((256, 768), eps=None, elementwise_affine=True)
        (attention): RoPEMaskedMultiheadAttention(
          (heads): ModuleList(
            (0-15): 16 x RoPEMaskedAttentionHead(
              (w_q): Linear(in_features=768, out_features=48, bias=True)
              (w_k): Linear(in_features=768, out_features=48, bias=True)
              (w_v): Linear(in_features=768, out_features=48, bias=True)
            )
          )
          (linear): Linear(in_features=768, out_features=768, bias=True)
        )
        (feedforward): Sequential(
          (0): SwiGLU(
            (linear1): Linear(in_features=768, out_features=1024, bias=True)
            (linear2): Linear(in_features=768, out_features=1024, bias=True)
            (silu): SiLU()
          )
          (1): Linear(in_features=1024, out_features=768, bias=True)
        )
      )
    )
  

In [13]:
llama_model.push_to_hub("custom-llama")

CommitInfo(commit_url='https://huggingface.co/TmBoris/custom-llama/commit/899719fa13d51e773ff3153e99ee69d5c88c4c25', commit_message='Upload LLaMA_model', commit_description='', oid='899719fa13d51e773ff3153e99ee69d5c88c4c25', pr_url=None, repo_url=RepoUrl('https://huggingface.co/TmBoris/custom-llama', endpoint='https://huggingface.co', repo_type='model', repo_id='TmBoris/custom-llama'), pr_revision=None, pr_num=None)

In [14]:
# !git clone --depth 1 https://github.com/EleutherAI/lm-evaluation-harness
# %cd lm-evaluation-harness
# %pip install -e .

In [15]:
# %cd ..

In [16]:
from transformers import AutoModelForCausalLM 

tmp_model = AutoModelForCausalLM.from_pretrained('TmBoris/custom-llama', trust_remote_code=True)

A new version of the following files was downloaded from https://huggingface.co/TmBoris/custom-llama:
- LLaMA_config.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/TmBoris/custom-llama:
- swish.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/TmBoris/custom-llama:
- llama_block.py
- swish.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/TmBoris/custom-llama:
- LLaMA.py
- llama_block.py
. Make sure to double-check they do not contain any added

model initialized


In [17]:
!lm_eval --model hf \
            --model_args pretrained=TmBoris/custom-llama \
            --tasks tinyMMLU --batch_size 1 \
            --output_path saved/metrics/llama_trained_v2 \
            --log_samples \
            --device cuda:0 \
            --trust_remote_code

model initialized


/home/jupyter/.local/lib/python3.10/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/usr/local/lib/python3.10/dist-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
2024-11-08 17:18:28.400197: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/torchvision/datapoints/__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are 

Exception: Process exited with code 1

In [ ]:
import json
import numpy as np
import tinyBenchmarks as tb


file_path = "saved/metrics/llama_trained_v2/TmBoris__custom-llama/samples_tinyMMLU_2024-11-08T15-52-28.131904.jsonl"

results = []
with open(file_path, 'r') as file:
    for i, line in enumerate(file):
        results.append(json.loads(line))

# Ensuring correct order of outputs  
results = sorted(results, key=lambda x: x['doc_id'])

y = np.array([float(item['acc_norm']) for item in results])

metric_results = tb.evaluate(y, 'mmlu')
print(metric_results)

In [ ]:
# %pip install git+https://github.com/felipemaiapolo/tinyBenchmarks

In [ ]:
llama_model